modLoader="javafml"
loaderVersion="[47,)"
license="Botania License"
issueTrackerURL="https://github.com/Vazkii/Botania/issues"
logoFile="logo.png"

[[mods]]
modId="botania"
version="${file.jarVersion}"
displayName="Botania"
displayURL="https://botaniamod.net"
description="Botania is a mod that adds nature magic to Minecraft."
authors="Vazkii, wiiv, williewillus, dylan4ever, Hubry, Alwinfy, artemisSystem, Falkory220, Wormbo"
credits="Azanor, Flaxbeard, Futureazoo, Rorax, Lorc, Adubbz, WTFG33ks, Auric245524, MegaManki, Kain Vinosec, Kihira, mDiyo, Mikeemoo, ChickenBones, PowerCrystals, cpw, quat1024, ToMe25, Eutro and others"

itemIcon="botania:cosmetic_botanist_emblem" # custom icon for Catalogue's mod list
configBackground="botania:textures/block/livingrock_bricks.png" # background for Configured's generated config screen

[[mixins]]
config="botania_xplat.mixins.json"

[[mixins]]
config="botania_forge.mixins.json"

[[dependencies.botania]]
    modId="neoforge"
    type="required"
    versionRange="[20.4.3,)"

[[dependencies.botania]]
    modId="patchouli"
    type="required"
    versionRange="[1.20.4-85,)"

[[dependencies.botania]]
    modId="curios"
    type="required"
    versionRange="[1.20.4-7.4,)"

[[dependencies.botania]]
    modId="gardenofglass"
    type="optional"
    versionRange="[1.12,)"

[[dependencies.botania]]
    modId="ears"
    type="optional"
    versionRange="[1.4.6,)"
