modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${license}"
issueTrackerURL = "${issues_url}"

[[mods]]
modId = "botania"
version = "${version}"
displayName = "${mod_name}"
displayURL = "${website_url}"
logoFile = "logo.png"
description = '''${description}'''
authors = "Vazkii, wiiv, williewillus, dylan4ever, Hubry, Alwinfy, artemisSystem, Falkory220, Wormbo"
credits = "Azanor, Flaxbeard, Futureazoo, Rorax, Lorc, Adubbz, WTFG33ks, Auric245524, MegaManki, Kain Vinosec, Kihira, mDiyo, Mikeemoo, ChickenBones, PowerCrystals, cpw, quat1024, ToMe25, Eutro and others"

itemIcon = "botania:cosmetic_botanist_emblem" # custom icon for Catalogue's mod list
configBackground = "botania:textures/block/livingrock_bricks.png" # background for Configured's generated config screen

[[mixins]]
config = "${mod_id}.xplat.mixins.json"

[[mixins]]
config = "${mod_id}.neoforge.mixins.json"

[[dependencies.botania]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"

[[dependencies.botania]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"

[[dependencies.botania]]
modId = "patchouli"
type = "required"
versionRange = "*"

[[dependencies.botania]]
modId = "curios"
type = "required"
versionRange = "*"

[[dependencies.botania]]
modId = "gardenofglass"
type = "optional"
versionRange = "*"

[[dependencies.botania]]
modId = "ears"
type = "optional"
versionRange = "*"
